// ...existing code...
const { updateSubscriptionValue } = require('../controllers/adminController');
// ...existing code...
router.put('/update-subscription-value', updateSubscriptionValue);
// ...existing code...
